### ISSUE TITLE
selam

### ISSUE THREAD

**Issue by ebicoglu** [muratg/pureable#1]
Murat selam, ben Alper, [ABP Framework](https://github.com/abpframework/abp), [ASP.NET Boilerplate framework](https://github.com/aspnetboilerplate/aspnetboilerplate/), [ASP.NET Zero](https://aspnetzero.com/)  ürünlerinin contributor ve mimarlarından biriyim. Senin de ASP.NET takımında olduğunu biliyorum. Bu anlamda, fikir alışverişinde bulunmak ve yazılım konularında konuşmak adına senle tanışmak isterim. alper.ebicoglu@volosoft.com mail adresim. selam maili atarsan  sevinirim 👋

**Comment by muratg** [comment]
Selamlar! Mail sent :) Gelmediyse spam/junk'a bakip pingler misin?  Konusmak uzere.
